// lib/exporters.js

const puppeteer = require("puppeteer");
const htmlToDocx = require("html-to-docx");

/**
 * Wrap edited HTML in a printable document layout.
 * This HTML is what gets converted to PDF.
 */
function createPrintableHtml({
    documentTitle,
    metadataLines,
    editedHtml,
    cssFileUrl,
}) {
    const metadataHtml = metadataLines
        .map((line) => `<span>${escapeHtml(line)}</span>`)
        .join(`<span class="meta-separator">•</span>`);

    return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(documentTitle)}</title>
    <link rel="stylesheet" href="${cssFileUrl}">
  </head>
  <body>
    <div class="document-page">
      <header class="document-header">
        <h1 class="document-title">${escapeHtml(documentTitle)}</h1>
        <div class="document-meta">${metadataHtml}</div>
      </header>

      <main class="document-content">
        ${editedHtml || ""}
      </main>

      <footer class="document-footer">
        Draft generated by the Document Generator. Review before use.
      </footer>
    </div>
  </body>
</html>`;
}

/**
 * Convert printable HTML into a PDF buffer.
 */
async function generatePdfFromHtml(printableHtml) {
    const browser = await puppeteer.launch({
        headless: "new",
        args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });

    try {
        const page = await browser.newPage();
        await page.setContent(printableHtml, { waitUntil: "networkidle0" });

        return await page.pdf({
            format: "Letter",
            printBackground: true,
            margin: {
                top: "0.5in",
                right: "0.5in",
                bottom: "0.5in",
                left: "0.5in",
            },
        });
    } finally {
        await browser.close();
    }
}

/**
 * Convert edited HTML into a DOCX buffer.
 */
async function generateDocxFromHtml(editedHtml) {
    return htmlToDocx(editedHtml || "<p></p>", null, {
        pageNumber: true,
        footer: true,
    });
}

/**
 * Basic HTML escaping for titles / metadata.
 */
function escapeHtml(text) {
    return String(text || "")
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
}

module.exports = {
    createPrintableHtml,
    generatePdfFromHtml,
    generateDocxFromHtml,
};